### 1. What is a Python library? Why do we use Python libraries?

### Python libraries are essential tools that enhance the capabilities of the Python programming language and enable developers to build powerful, efficient, and scalable applications across various domains.

### 2. What is the difference between Numpy array and List?

In [ ]:
NumPy Array:
Homogeneous multidimensional array
More memory efficient due to contiguous allocation.
Faster for numerical computations
Extensive mathematical and array operations
Scientific computing, data analysis, machine learning


---------------------------------------------------------------------

Python List:
Heterogeneous one-dimensional array
Less memory efficient due to scattered references
Slower for numerical computations
General-purpose operations
Wide range of applications

### 3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [8]:
import numpy as np

In [9]:
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [11]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
arr.shape

(3, 4)

In [12]:
arr.ndim

2

In [13]:
arr.size

12

### 4. Write python code to access the first row of the following array?

In [14]:
arr=[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [16]:
arr=np.array(arr)

In [17]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [18]:
arr[0]

array([1, 2, 3, 4])

### 5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [20]:
arr=np.array(
[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

In [34]:
arr[2][3]

12

### 6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [35]:
arr=np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

In [40]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
arr[:,1::2]# fisrt slicing is for row to get all rows , second slicing is from start from 1 with step 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [42]:
arr= np.random.rand(3, 3)
arr

array([[0.70997745, 0.26165725, 0.15040944],
       [0.30187085, 0.28150419, 0.5277128 ],
       [0.9352634 , 0.50831119, 0.12705047]])

### 8.Describe tthe difference between np.random.rand and np.random.randn

In [ ]:
np.random.rand:
This function generates random numbers from a uniform distribution over the interval [0, 1).
It takes the shape of the output array as arguments, rather than specifying the mean and standard deviation.
For example, np.random.rand(3, 2) would generate a 3x2 array of random numbers between 0 and 1.

                                                                                      np.random.randn:
This function generates random numbers from a standard normal distribution (mean of 0 and standard deviation of 1), also known as a Gaussian distribution or the "bell curve".
It takes the shape of the output array as arguments, similarly to np.random.rand.
For example, np.random.randn(3, 2) would generate a 3x2 array of random numbers sampled from a standard normal distribution.

### 9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [44]:
arr=np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
np.expand_dims(arr,axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

### 10. How to transpose the following array in NumPy?

In [46]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

### 11. Consider the following matrix:

Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B:[[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [52]:
Matrix_a=np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
Matrix_b=np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])


In [53]:
Matrix_a,Matrix_b

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

In [55]:
#Index wise multiplication
Matrix_a*Matrix_b

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [62]:
arv=Matrix_b.reshape(4,3)#i need to change the shape of the matrix because of dot prod

In [64]:
#matrix multiplication
mtr=np.dot(Matrix_a,arv)
mtr  

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

In [66]:
#add both the matrics
Matrix_a+Matrix_b

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [ ]:
#subtrcat the  b from a

In [68]:
Matrix_b-Matrix_a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [69]:
#divide from B by a
Matrix_b/Matrix_a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### 12.which function in numpy can be used for swap the byte order of an array

In [70]:
arr = np.array([1, 256], dtype=np.int16)

# Swap the byte order
swapped_arr = arr.byteswap()

print("Original array:")
print(arr)
print("Swapped array:")
print(swapped_arr)

Original array:
[  1 256]
Swapped array:
[256   1]


### 13.What is the significant of the  np.linalg.inv function?

In [ ]:
np.linalg.inv is a fundamental function in linear algebra and numerical computing, providing the capability to compute the inverse of matrices, which finds applications across various domains.

### 14.what does the np.reshape function do  and how it used?

In [ ]:
np.reshape is a versatile function in NumPy for changing the shape of arrays without modifying the underlying data. It is commonly used in array manipulation and data preprocessing tasks in scientific computing, machine learning, and data analysis.

### 15.what is broadcasting in numpy

In [ ]:
np.reshape is a versatile function in NumPy for changing the shape of arrays without modifying the underlying data. It is commonly used in array manipulation and data preprocessing tasks in scientific computing, machine learning, and data analysis.